### ISSUE TITLE
Updating of loopy make `python -c "import firedrake"` failed

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake-spack#27]
The command raises the error "ImportError: cannot import name 'CachedCombineMapper' from 'pymbolic.mapper' ". It seems that the new version `loopy` needs the `develop` version `py-pymbolic` and the package `py-immutables`.

Traceback after install firedrake:
```
[firedrake-real-int32] [z2yang@ws2 firedrake-real-int32]$ python -c "import firedrake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/firedrake/__init__.py", line 69, in <module>
    from pyop2 import op2                        # noqa: F401
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/__init__.py", line 4, in <module>
    from pyop2.op2 import *  # noqa
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/op2.py", line 38, in <module>
    from pyop2.configuration import configuration
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/configuration.py", line 38, in <module>
    from loopy.target.c import CWithGNULibcTarget
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/loopy/__init__.py", line 24, in <module>
    from loopy.symbolic import (
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/loopy/symbolic.py", line 43, in <module>
    from pymbolic.mapper import (
ImportError: cannot import name 'CachedCombineMapper' from 'pymbolic.mapper' (/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pymbolic/mapper/__init__.py)
```

Traceback after installing `py-pymbolic@develop`:
```
[firedrake-real-int32] [z2yang@ws2 firedrake-real-int32]$ python -c "import firedrake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/firedrake/__init__.py", line 69, in <module>
    from pyop2 import op2                        # noqa: F401
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/__init__.py", line 4, in <module>
    from pyop2.op2 import *  # noqa
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/op2.py", line 38, in <module>
    from pyop2.configuration import configuration
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/pyop2/configuration.py", line 38, in <module>
    from loopy.target.c import CWithGNULibcTarget
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/loopy/__init__.py", line 24, in <module>
    from loopy.symbolic import (
  File "/home/z2yang/opt/firedrake-real-int32/.spack-env/view/lib/python3.10/site-packages/loopy/symbolic.py", line 52, in <module>
    import immutables
ModuleNotFoundError: No module named 'immutables'
```

**Comment by connorjward** [comment]
Yes immutables is a new dependency of loopy. I forgot when I updated our loopy branch that spack doesn't respect Python declaring dependencies. A new spack package may be needed.

**Comment by lrtfm** [comment]
As spack has package py-immutables, we just need to add it as a dependency.
